In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

In [4]:
print(scalar)
print(vector)
print(matrix)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])


In [6]:
print(variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [7]:
random_tensor = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.int32)

In [8]:
print(random_tensor)

tf.Tensor(
[[6 8 2]
 [3 9 0]], shape=(2, 3), dtype=int32)


In [9]:
print(random_tensor)

tf.Tensor(
[[6 8 2]
 [3 9 0]], shape=(2, 3), dtype=int32)


In [10]:
# Creating a 2x3 matrix tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)
print("Rank:", tf.rank(matrix).numpy())

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Data Type: <dtype: 'int32'>
Rank: 2


Manipulating Tensor Shapes:
TensorFlow provides several operations to reshape and manipulate tensors:

#Reshape: Change the shape of a tensor without altering its data.
reshaped = tf.reshape(tensor, new_shape)

#Expand Dimensions: Add a new axis.
expanded = tf.expand_dims(tensor, axis=0)

#Squeeze Dimensions: Remove axes of size 1.
squeezed = tf.squeeze(tensor, axis=0)

#Transpose: Permute the dimensions of a tensor.
transposed = tf.transpose(tensor, perm=[1, 0, 2])

In [12]:
# Creating a tensor with a specific data type
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)

Casting Between Data Types:

TensorFlow allows for casting tensors from one data type to another using the tf.cast function:

In [13]:
# Casting float tensor to int tensor
casted_tensor = tf.cast(float_tensor, dtype=tf.int32)

In [14]:
print(casted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [15]:
# Creating a 3-D tensor (batch of 2 images, 3x3 pixels, 1 channel)
tensor = tf.constant([
    [[[255], [0], [127]],
     [[255], [0], [127]],
     [[255], [0], [127]]],
    
    [[[255], [0], [127]],
     [[255], [0], [127]],
     [[255], [0], [127]]]
], dtype=tf.uint8)

print("Tensor:\n", tensor)
print("Shape:", tensor.shape)
print("Data Type:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())

# Reshaping the tensor to flatten the images
reshaped_tensor = tf.reshape(tensor, (2, 9))
print("Reshaped Tensor:\n", reshaped_tensor)
print("New Shape:", reshaped_tensor.shape)

Tensor:
 tf.Tensor(
[[[[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]]


 [[[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]]], shape=(2, 3, 3, 1), dtype=uint8)
Shape: (2, 3, 3, 1)
Data Type: <dtype: 'uint8'>
Rank: 4
Reshaped Tensor:
 tf.Tensor(
[[255   0 127 255   0 127 255   0 127]
 [255   0 127 255   0 127 255   0 127]], shape=(2, 9), dtype=uint8)
New Shape: (2, 9)


Arithmetic Operations
TensorFlow supports a wide range of arithmetic operations that can be performed element-wise or through matrix operations.

Element-Wise Operations:

In [16]:
# Addition (tf.add or +):
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.add(a, b)
# Alternatively: c = a + b
print(c)  # Output: [5, 7, 9]

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [17]:
# Subtraction (tf.subtract or -):
c = tf.subtract(a, b)
# Alternatively: c = a - b
print(c)  # Output: [-3, -3, -3]

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [18]:
# Multiplication (tf.multiply or *):
c = tf.multiply(a, b)
# Alternatively: c = a * b
print(c)  # Output: [4, 10, 18]

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [20]:
# Division (tf.divide or /):
c = tf.divide(b, a)
# Alternatively: c = b / a
print(c)  # Output: [4.0, 2.5, 2.0]

tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)


Matrix Operations:

In [21]:
# Matrix Multiplication (tf.matmul):
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
product = tf.matmul(matrix1, matrix2)
print(product)
# Output:
# [[19 22]
#  [43 50]]

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [22]:
# Transpose (tf.transpose):
transposed = tf.transpose(matrix1)
print(transposed)
# Output:
# [[1 3]
#  [2 4]]

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


Reshaping Tensors
Reshaping changes the structure of a tensor without altering its data. This is particularly useful when preparing data for different layers in a neural network.

In [23]:
# Original tensor of shape (2, 3)
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original Shape:", tensor.shape)  # (2, 3)

# Reshaping to (3, 2)
reshaped = tf.reshape(tensor, (3, 2))
print("Reshaped Tensor:\n", reshaped)
print("New Shape:", reshaped.shape)  # (3, 2)

Original Shape: (2, 3)
Reshaped Tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
New Shape: (3, 2)


Slicing and Indexing
Slicing allows you to extract specific parts of a tensor, which is essential for tasks like data augmentation and preprocessing.

In [24]:
# Creating a 3-D tensor
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

# Slicing the first two matrices
sliced = tensor[:2]
print("Sliced Tensor:\n", sliced)

# Accessing a specific element
element = tensor[1, 1, 1]
print("Specific Element:", element)  # Output: 8

Sliced Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Specific Element: tf.Tensor(8, shape=(), dtype=int32)



Broadcasting
Broadcasting is a technique that allows TensorFlow to perform operations on tensors of different shapes by automatically expanding their dimensions to make them compatible.

In [25]:
# Tensor A of shape (3, 1)
A = tf.constant([[1], [2], [3]])

# Tensor B of shape (1, 4)
B = tf.constant([[10, 20, 30, 40]])

# Broadcasting to shape (3, 4)
C = A + B
print("Broadcasted Tensor:\n", C)

Broadcasted Tensor:
 tf.Tensor(
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]], shape=(3, 4), dtype=int32)


Reduction Operations
Reduction operations summarize the elements of a tensor along specific dimensions.


In [26]:
#Sum (tf.reduce_sum):
tensor = tf.constant([[1, 2], [3, 4]])
sum_all = tf.reduce_sum(tensor)
sum_axis0 = tf.reduce_sum(tensor, axis=0)
sum_axis1 = tf.reduce_sum(tensor, axis=1)
print("Sum All:", sum_all)           # 10
print("Sum Axis 0:", sum_axis0)     # [4, 6]
print("Sum Axis 1:", sum_axis1)     # [3, 7]

Sum All: tf.Tensor(10, shape=(), dtype=int32)
Sum Axis 0: tf.Tensor([4 6], shape=(2,), dtype=int32)
Sum Axis 1: tf.Tensor([3 7], shape=(2,), dtype=int32)


In [27]:
# Mean (tf.reduce_mean):
mean_all = tf.reduce_mean(tensor)
print("Mean All:", mean_all)         # 2.5

Mean All: tf.Tensor(2, shape=(), dtype=int32)


In [28]:
# Maximum (tf.reduce_max):
max_all = tf.reduce_max(tensor)
print("Max All:", max_all)           # 4

Max All: tf.Tensor(4, shape=(), dtype=int32)


Reshaping and Expanding Dimensions
Altering the shape of tensors is often necessary to align data for specific operations or neural network layers.

In [29]:
# Original tensor of shape (2, 3)
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Normal Tensor Shape", tensor.shape)

# Adding a new axis to make it (2, 3, 1)
expanded = tf.expand_dims(tensor, axis=-1)
print("Expanded Tensor Shape:", expanded.shape)  # (2, 3, 1)

# Removing the added axis
squeezed = tf.squeeze(expanded, axis=-1)
print("Squeezed Tensor Shape:", squeezed.shape)  # (2, 3)


Normal Tensor Shape (2, 3)
Expanded Tensor Shape: (2, 3, 1)
Squeezed Tensor Shape: (2, 3)


Concatenation and Stacking
Combining tensors is a common operation, especially when dealing with batches of data.


In [30]:
# Concatenation (tf.concat):
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Concatenate along axis 0
concat_axis0 = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated along axis 0:\n", concat_axis0)

# Concatenate along axis 1
concat_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("Concatenated along axis 1:\n", concat_axis1)

Concatenated along axis 0:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Concatenated along axis 1:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)


In [31]:
#  Stacking (tf.stack):
# Stack tensors along a new axis
stacked = tf.stack([tensor1, tensor2], axis=0)
print("Stacked Tensor:\n", stacked)
print("Stacked Shape:", stacked.shape)  # (2, 2, 2)

Stacked Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Stacked Shape: (2, 2, 2)


Advanced Operations
While basic operations are essential, TensorFlow also offers advanced operations for more complex data manipulations.

In [32]:
# One-Hot Encoding (tf.one_hot):
indices = tf.constant([0, 1, 2, 1])
depth = 3
one_hot = tf.one_hot(indices, depth)
print("One-Hot Encoded Tensor:\n", one_hot)

One-Hot Encoded Tensor:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]], shape=(4, 3), dtype=float32)


In [33]:
# Matrix Inversion (tf.linalg.inv):
matrix = tf.constant([[1., 2.], [3., 4.]])
inverse = tf.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse)

Inverse of Matrix:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


In [34]:
# Eigenvalues and Eigenvectors (tf.linalg.eig):
matrix = tf.constant([[1., 2.], [3., 4.]])
eigenvalues, eigenvectors = tf.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64)
Eigenvectors:
 tf.Tensor(
[[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]], shape=(2, 2), dtype=complex64)


In [35]:


# Creating two tensors
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Arithmetic Operations
addition = a + b
multiplication = a * b
matrix_product = tf.matmul(a, b)

print("Addition:\n", addition)
print("Element-Wise Multiplication:\n", multiplication)
print("Matrix Product:\n", matrix_product)

# Reshaping
reshaped = tf.reshape(a, (4, 1))
print("Reshaped Tensor:\n", reshaped)

# Slicing
sliced = a[:, 1]
print("Sliced Tensor:", sliced)

# Reduction
sum_all = tf.reduce_sum(a)
print("Sum of All Elements:", sum_all)

Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-Wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Product:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Reshaped Tensor:
 tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
Sliced Tensor: tf.Tensor([2 4], shape=(2,), dtype=int32)
Sum of All Elements: tf.Tensor(10, shape=(), dtype=int32)


Constants
A Constant in TensorFlow is an immutable tensor whose value cannot be changed after it is defined. Constants are used to hold fixed values that do not need to be updated during the execution of the computational graph, such as weights in certain layers or fixed hyperparameters.

In [36]:
import tensorflow as tf

# Creating a constant tensor
const_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print("Constant Tensor:", const_tensor)

Constant Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


A Variable in TensorFlow is a mutable tensor that can be updated during the execution of the computational graph. Variables are typically used to store and update the parameters of machine learning models, such as weights and biases, during training.


In [37]:
# Creating a variable tensor
var_tensor = tf.Variable([1.0, 2.0, 3.0], dtype=tf.float32)
print("Variable Tensor:", var_tensor)

Variable Tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [38]:
# Initializing a variable with zeros
var_zero = tf.Variable(tf.zeros([2, 3]), name='zero_initializer')

# Initializing a variable with random values
var_random = tf.Variable(tf.random.normal([2, 3]), name='random_initializer')

In [39]:
weight = tf.Variable(tf.random.normal([784, 256]), name='weights')
bias = tf.constant([0.1] * 256, dtype=tf.float32, name='biases')

In [40]:
with tf.name_scope('layer1'):
    weights = tf.Variable(tf.random.normal([784, 256]), name='weights')
    biases = tf.constant([0.1] * 256, dtype=tf.float32, name='biases')

In [41]:
import tensorflow as tf

# Define Constants for input data
X = tf.constant([[1.0], [2.0], [3.0], [4.0]], dtype=tf.float32)  # Input features
Y = tf.constant([[2.0], [4.0], [6.0], [8.0]], dtype=tf.float32)  # Target values

# Define Variables for model parameters (weights and bias)
W = tf.Variable([[0.0]], dtype=tf.float32, name='weight')
b = tf.Variable([0.0], dtype=tf.float32, name='bias')

# Define the linear model
def linear_model(X):
    return tf.matmul(X, W) + b

# Define the loss function (Mean Squared Error)
def loss_fn(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

# Define the optimizer
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Training loop
for epoch in range(1000):
    with tf.GradientTape() as tape:
        y_pred = linear_model(X)
        loss = loss_fn(y_pred, Y)
    
    # Compute gradients
    gradients = tape.gradient(loss, [W, b])
    
    # Update variables
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.numpy()}, W = {W.numpy()}, b = {b.numpy()}")

# Final model parameters
print("Trained Weights:", W.numpy())
print("Trained Bias:", b.numpy())

Epoch 0: Loss = 30.0, W = [[0.29999998]], b = [0.09999999]
Epoch 100: Loss = 0.03408462926745415, W = [[1.8468075]], b = [0.45040485]
Epoch 200: Loss = 0.01871202513575554, W = [[1.8864939]], b = [0.33372158]
Epoch 300: Loss = 0.010272666811943054, W = [[1.9158992]], b = [0.24726659]
Epoch 400: Loss = 0.005639578215777874, W = [[1.9376867]], b = [0.18320896]
Epoch 500: Loss = 0.0030960547737777233, W = [[1.9538298]], b = [0.13574634]
Epoch 600: Loss = 0.001699708285741508, W = [[1.9657906]], b = [0.10057957]
Epoch 700: Loss = 0.0009331251494586468, W = [[1.974653]], b = [0.0745233]
Epoch 800: Loss = 0.0005122720031067729, W = [[1.9812194]], b = [0.05521719]
Epoch 900: Loss = 0.00028123249649070203, W = [[1.9860847]], b = [0.04091255]
Trained Weights: [[1.9896587]]
Trained Bias: [0.03040474]


In [42]:
import tensorflow as tf

# Define two constant tensors
a = tf.constant(2.0)
b = tf.constant(3.0)

# Define an addition operation
c = tf.add(a, b)
print("Operation:", c)

Operation: tf.Tensor(5.0, shape=(), dtype=float32)


 Keras Input Layers:

Use tf.keras.Input or tf.keras.layers.Input to define input tensors in Keras models.

In [ ]:
from tensorflow.keras.layers import Input
input_layer = Input(shape=(784,), name='input_layer')

Eager Execution with Direct Data Feeding:

Directly pass data to functions and models without the need for placeholders.

In [ ]:
import tensorflow as tf

# Define a simple operation
def add(a, b):
    return a + b

# Execute the operation with actual data
result = add(2.0, 3.0)
print(result.numpy())  # Output: 5.0

tf.function and Autograph:

Decorate Python functions with @tf.function to compile them into optimized TensorFlow graphs, allowing for dynamic and flexible data inputs.

In [ ]:
import tensorflow as tf

@tf.function
def compute(a, b):
    return a * b + 2

# Call the function with data
print(compute(3.0, 4.0).numpy())  # Output: 14.0

Data Pipelines with tf.data:

Utilize the tf.data API to build efficient and scalable data input pipelines.

In [ ]:
import tensorflow as tf

# Create a dataset
dataset = tf.data.Dataset.from_tensor_slices((train_X, train_Y))
dataset = dataset.batch(32)

# Iterate over the dataset
for batch_X, batch_Y in dataset:
    # Perform training step
    pass

Direct Tensor Passing in Keras Models:

Pass NumPy arrays or TensorFlow tensors directly to Keras models for training and inference.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Define a simple model
model = Sequential([
    Dense(10, activation='relu', input_shape=(784,)),
    Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Generate dummy data
X = np.random.rand(100, 784)
Y = np.random.rand(100, 1)

# Train the model
model.fit(X, Y, epochs=5)

Migrating from Placeholders to TensorFlow 2.x
For developers transitioning from TensorFlow 1.x to 2.x, migrating code that utilizes Placeholders involves adopting the new data input mechanisms. Here's a step-by-step guide to refactoring code:

Remove Placeholders:
Eliminate the use of tf.placeholder and feed_dict by adopting direct data passing.
Use Keras Input Layers:
Define input layers using tf.keras.Input when building Keras models.
Leverage tf.function:
Decorate functions with @tf.function to enable graph execution where performance is critical.
Adopt the tf.data API:
Build data pipelines using the tf.data API for efficient data handling and preprocessing.
Utilize Keras Model Training APIs:
Use model.fit, model.evaluate, and model.predict to manage training, evaluation, and inference without manual session management.

Example Migration:

TensorFlow 1.x Code with Placeholders:

In [ ]:
import tensorflow as tf

# Define placeholders
X = tf.placeholder(tf.float32, shape=[None, 784])
Y = tf.placeholder(tf.float32, shape=[None, 10])

# Define a simple neural network
W = tf.Variable(tf.random_normal([784, 10]))
b = tf.Variable(tf.random_normal([10]))
logits = tf.matmul(X, W) + b

# Define loss and optimizer
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=logits))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5).minimize(loss)

# Start a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training loop
    for epoch in range(1000):
        batch_X, batch_Y = get_next_batch()  # Assume this function fetches a batch
        sess.run(optimizer, feed_dict={X: batch_X, Y: batch_Y})

Refactored TensorFlow 2.x Code without Placeholders:

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Define a simple neural network using Keras
model = Sequential([
    Dense(10, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.5),
              loss='categorical_crossentropy')

# Generate dummy data
X_train = np.random.rand(1000, 784)
Y_train = tf.keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)

# Train the model
model.fit(X_train, Y_train, epochs=1000, batch_size=32)